version: 2

project_name: llmsa

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/llmsa
    binary: llmsa
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^style:"
      - "^Merge"

dockers:
  - image_templates:
      - "ghcr.io/ogulcanaydogan/llmsa:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile
    goarch: amd64
  - image_templates:
      - "ghcr.io/ogulcanaydogan/llmsa:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    dockerfile: Dockerfile
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/ogulcanaydogan/llmsa:{{ .Version }}"
    image_templates:
      - "ghcr.io/ogulcanaydogan/llmsa:{{ .Version }}-amd64"
      - "ghcr.io/ogulcanaydogan/llmsa:{{ .Version }}-arm64"
  - name_template: "ghcr.io/ogulcanaydogan/llmsa:latest"
    image_templates:
      - "ghcr.io/ogulcanaydogan/llmsa:{{ .Version }}-amd64"
      - "ghcr.io/ogulcanaydogan/llmsa:{{ .Version }}-arm64"
